language: node_js

sudo: false

node_js:
  - "12"

cache:
  yarn: true
  directories:
    - node_modules

branches:
  only:
    - master

env:
  global:
    - GITHUB_REPO: github.com/suntao123671/vuepress

before_install:
  - export TZ=Asia/Shanghai

script:
  - npm build
